
// CREATE NEW USER
POST http://localhost:6000/auth/register
Content-Type: application/json

{
    "firstname": "test",
    "lastname": "user",
    "email": "testuser@gmail.com",
    "password": "Testing123.56"
}

// LOGIN USER
POST http://localhost:6000/auth/login
Content-Type: application/json

{
    "email": "testuser@gmail.com",
    "password": "Testing123.56"
}