
// CREATE NEW USER
POST http://localhost:6000/auth/register
Content-Type: application/json

{
    "firstname": "john",
    "lastname": "doe",
    "email": "johndoe@gmail.com",
    "password": "Adetomi.54"
}

// LOGIN USER
POST http://localhost:6000/auth/login
Content-Type: application/json

{
    "email": "johndoe",
    "password": "Adetomi.54"
}