use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Error {
    AdminNotSet = 1,
    TokenAlreadyIssued = 2,
    TokenNotFound = 3,
    Unauthorized = 4,
    TokenExpired = 5,
    InvalidExpiryDate = 6,
    InvalidEventDetails = 7,
    InvalidPaymentAmount = 8,
    InvalidPaymentToken = 9,
    SubscriptionNotFound = 10,
    UsdcContractNotSet = 11,
    AttendanceLogFailed = 12,
    SubscriptionAlreadyExists = 13,
    InsufficientBalance = 14,
    TimestampOverflow = 15,
    MetadataNotFound = 16,
    MetadataDescriptionTooLong = 17,
    MetadataTooManyAttributes = 18,
    MetadataAttributeKeyTooLong = 19,
    MetadataTextValueTooLong = 20,
    MetadataValidationFailed = 21,
    InvalidMetadataVersion = 22,
    // Tier management errors (30-50)
    TierNotFound = 30,
    TierAlreadyExists = 31,
    TierNotActive = 32,
    InvalidTierPrice = 33,
    InvalidTierLevel = 34,
    TierHasActiveSubscriptions = 35,
    InvalidTierChange = 36,
    TierChangeNotFound = 37,
    TierChangeAlreadyProcessed = 38,
    CannotDowngradeToHigherTier = 39,
    CannotUpgradeToLowerTier = 40,
    PromoCodeInvalid = 41,
    PromoCodeExpired = 42,
    PromoCodeMaxRedemptions = 43,
    PromotionNotFound = 44,
    PromotionAlreadyExists = 45,
    InvalidDiscountPercent = 46,
    InvalidPromoDateRange = 47,
    FeatureNotAvailable = 48,
    UserLimitExceeded = 49,
    StorageLimitExceeded = 50,
}
