export enum AuditAction {
  MEMBER_SUSPENDED = 'MEMBER_SUSPENDED',
  MEMBER_ACTIVATED = 'MEMBER_ACTIVATED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_STATUS_OVERRIDE = 'BOOKING_STATUS_OVERRIDE',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
  WORKSPACE_DELETED = 'WORKSPACE_DELETED',
  PROMO_CODE_CREATED = 'PROMO_CODE_CREATED',
  PROMO_CODE_DISABLED = 'PROMO_CODE_DISABLED',
}
