PATCH http://localhost:6000/users/095d59e8-e65f-4f91-a47e-828fe0310ffc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOTVkNTllOC1lNjVmLTRmOTEtYTQ3ZS04MjhmZTAzMTBmZmMiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIiwiaWF0IjoxNzU5MjQzNDUyLCJleHAiOjE3NTkzMjk4NTJ9.dRNBWjqjWVjmum3_FwkQOoFbtJoA4sMYaAiw51vYWAI

{
    "username": "aboki"
}